BitirmeCalismasi/Controllers/AboutController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BitirmeCalismasi.Controllers
{
    public class AboutController : Controller
    {
        AboutManager abm = new AboutManager(new EfAboutDal());
        public ActionResult Index()
        {
            var aboutvalues = abm.GetList();
            return View(aboutvalues);
        }

        [HttpGet]
        public ActionResult AddAbout()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddAbout(About about )
        {
            abm.AboutAddBL(about);
            return RedirectToAction("Index");
        }

        public PartialViewResult AboutPartial()
        {
            return PartialView();
        }
    }
}

BitirmeCalismasi/Views/About/AboutPartial.cshtml
<button class="btn btn-primary" data-toggle="modal" data-target="#Modal1">
    Yeni Hakkımızda Yazı Girişi
</button>

<div class="modal" id="Modal1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title">Hakkımızda Metin Girişi</h2>

            </div>
            <form method="post" action="/About/AddAbout">
                <div class="modal-body">
                    <label>Hakkımda metin</label>
                    <input type="text" name="AboutDetails" class="form-control" />
                    <br />
                    <label>Hakkımda görsel 1</label>
                    <input type="text" name="AboutImage1" class="form-control" />
                    <br />
                    <label>Hakkımda görsel 2</label>
                    <input type="text" name="AboutImage2" class="form-control" />
                    <br />
                    <button class="btn btn-info">Kaydet</button>
                </div>

            </form>

        </div>


    </div>

</div>

BitirmeCalismasi/Views/About/Index.cshtml
@using EntityLayer.Concrete
@model List<About>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Hakkında Veri Listesi </h2>
<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>Hakkımda Başlığı</th>
        <th>Aktif Yap</th>
        <th>Pasif Yap</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <th>@item.AboutID</th>
            <th>Başlık</th>
            <th><a href="#" class="btn btn-warning">Aktif Yap</a></th>
            <th><a href="#" class="btn btn-danger">Pasif Yap</a></th>
        </tr>
    }

</table>




@Html.Action("AboutPartial","About")